"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { getSupabaseBrowserClient } from "../../lib/supabase/client";
import { fetchManagerChatMessages,sendManagerChatMessage,fetchOrganizationChatMembers,fetchDirectMessages,sendDirectMessage,fetchDirectUnreadCounts,markDirectMessagesRead } from "../../lib/data/managerChat";
export default function ManagerChat({organizationId,sites=[],siteFilter="all",session}){
 const [channel,setChannel]=useState(siteFilter!=="all"?siteFilter:"all"),[dm,setDm]=useState(null),[messages,setMessages]=useState([]),[members,setMembers]=useState([]),[online,setOnline]=useState({}),[unread,setUnread]=useState({}),[text,setText]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");const endRef=useRef(null);const site=channel==="all"?null:channel,myId=session?.user?.id;
 async function load(){if(!organizationId)return;setLoading(true);setError("");try{const rows=dm?await fetchDirectMessages(getSupabaseBrowserClient(),organizationId,dm.id,myId):await fetchManagerChatMessages(getSupabaseBrowserClient(),organizationId,site);setMessages(rows)}catch(e){setError(e?.message||"Could not load chat.")}finally{setLoading(false)}}
 useEffect(()=>{if(!organizationId)return;fetchOrganizationChatMembers(getSupabaseBrowserClient(),organizationId).then(setMembers).catch(e=>setError(e.message))},[organizationId]);
 async function refreshUnread(){if(!organizationId||!myId)return;try{setUnread(await fetchDirectUnreadCounts(getSupabaseBrowserClient(),organizationId,myId))}catch{}}
 useEffect(()=>{refreshUnread()},[organizationId,myId]);
 useEffect(()=>{load();if(dm&&organizationId&&myId){markDirectMessagesRead(getSupabaseBrowserClient(),organizationId,dm.id,myId).then(refreshUnread).catch(()=>{})}},[organizationId,channel,dm?.id]);
 useEffect(()=>{if(!organizationId||!myId)return;const s=getSupabaseBrowserClient(),p=s.channel(`org-presence-${organizationId}`,{config:{presence:{key:myId}}});const sync=()=>{const st=p.presenceState(),n={};Object.entries(st).forEach(([k,v])=>n[k]=v?.[0]||{});setOnline(n)};p.on("presence",{event:"sync"},sync).subscribe(async x=>{if(x==="SUBSCRIBED")await p.track({user_id:myId,online_at:new Date().toISOString()})});return()=>{p.untrack();s.removeChannel(p)}},[organizationId,myId]);
 useEffect(()=>{if(!organizationId)return;const s=getSupabaseBrowserClient(),ch=s.channel(`chat-events-${organizationId}-${myId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"manager_chat_messages",filter:`organization_id=eq.${organizationId}`},()=>{if(!dm)load()}).on("postgres_changes",{event:"INSERT",schema:"public",table:"manager_direct_messages",filter:`organization_id=eq.${organizationId}`},()=>{if(dm)load();refreshUnread()}).subscribe();return()=>s.removeChannel(ch)},[organizationId,channel,dm?.id,myId]);
 useEffect(()=>endRef.current?.scrollIntoView({behavior:"smooth"}),[messages.length]);
 const channels=useMemo(()=>["all",...sites],[sites]),others=members.filter(m=>m.id!==myId);
 async function send(e){e.preventDefault();const body=text.trim();if(!body)return;setText("");try{const s=getSupabaseBrowserClient();if(dm)await sendDirectMessage(s,{organizationId,recipientId:dm.id,body});else await sendManagerChatMessage(s,{organizationId,site,body});await load()}catch(e){setText(body);setError(e.message)}}
 const senderName=id=>members.find(m=>m.id===id)?.full_name||members.find(m=>m.id===id)?.email||"Member";
 return <section className="manager-chat-page"><header className="manager-chat-head"><div><span className="page-kicker">ORGANIZATION CHAT · REALTIME</span><h1>Team communication</h1><p>Only members of this MetrixIQ organization can access these conversations.</p></div><span className="chat-live">● {Object.keys(online).length} ONLINE {Object.values(unread).reduce((a,b)=>a+b,0)>0&&<strong>· {Object.values(unread).reduce((a,b)=>a+b,0)} UNREAD</strong>}</span></header><div className="manager-chat-shell chat-shell-people"><aside className="chat-channels"><b>CHANNELS</b>{channels.map(c=><button key={c} className={!dm&&channel===c?"active":""} onClick={()=>{setDm(null);setChannel(c)}}><span>#</span>{c==="all"?"All Sites":c}</button>)}</aside><main className="chat-room"><div className="chat-room-title"><div><b>{dm?`@ ${dm.full_name||dm.email}`:channel==="all"?"# All Sites":`# ${channel}`}</b><small>{dm?(online[dm.id]?"Online now":"Offline"):(channel==="all"?"Organization-wide channel":"Site channel")}</small></div></div>{error&&<div className="mgrv2-notice error">{error}</div>}<div className="chat-messages">{loading?<div className="chat-empty">Loading conversation…</div>:!messages.length?<div className="chat-empty"><b>No messages yet</b><span>Start the conversation.</span></div>:messages.map(m=>{const name=dm?senderName(m.sender_id):m.sender_name;return <article key={m.id}><i>{String(name).split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}</i><div><header><b>{m.sender_id===myId?"You":name}</b><time>{new Date(m.created_at).toLocaleString([],{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</time></header><p>{m.body}</p></div></article>})}<div ref={endRef}/></div><form className="chat-compose" onSubmit={send}><textarea value={text} maxLength={4000} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send(e)}}} placeholder={dm?`Message ${dm.full_name||dm.email}…`:`Message ${channel==="all"?"All Sites":channel}…`}/><button disabled={!text.trim()}>➤</button></form></main><aside className="chat-people"><header><b>MEMBERS</b><span>{members.length}</span></header><div>{others.map(m=><button key={m.id} className={dm?.id===m.id?"active":""} onClick={()=>setDm(m)}><i>{String(m.full_name||m.email||"M").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}<em className={online[m.id]?"online":"offline"}/></i><span><b>{m.full_name||m.email||"Member"}</b><small>{m.role||"member"} · {online[m.id]?"Online":"Offline"}</small></span>{unread[m.id]>0&&<em className="chat-unread">{unread[m.id]>99?"99+":unread[m.id]}</em>}</button>)}</div></aside></div></section>
}