export const metricAliases = {
  dcr: ["dcr", "dcr %", "delivery completion rate", "delivery completion rate %", "delivery completion", "completion rate", "completion rate %"],
  pod: ["pod", "pod %", "pod compliance", "pod compliance %", "photo on delivery", "photo on delivery %", "photo-on-delivery", "photo-on-delivery %", "photo on delivery compliance", "pod quality"],
  iadc: ["iadc", "iadc %", "in app delivery workflow", "in-app delivery workflow"],
  dwc: ["dwc", "dwc %", "delivery workflow compliance"],
  cc: ["cc", "contact compliance", "contact compliance %"],
  mentor_score: ["mentor score", "ementor score", "e mentor score", "fico", "fico score"],
  scorecard_score: ["total score", "total scorecard score", "scorecard score", "overall driver score"],
  concessions: ["concessions", "concession count", "concessions count", "total concessions", "total concession"],
  delivered: ["delivered", "delivered packages"],
  dnr: ["dnr", "packages delivered not received", "delivered not received", "dnr count"],
  dnr_dpmo: ["dnr dpmo", "delivered not received dpmo"],
  rts: ["rts", "packages returned to station", "returned to station", "rts count"],
  dsc_dpmo: ["dsc", "dsc dpmo", "delivery success conditions", "delivery success conditions dpmo"],
  lor: ["lor", "lor dpmo", "lost on road", "lost on road dpmo", "loss on route"],
  ce_dpmo: ["ce", "ce dpmo", "customer escalation", "customer escalation dpmo", "customer escalations"],
  cdf_dpmo: ["cdf", "cdf dpmo", "customer delivery feedback", "customer delivery feedback dpmo"],
  psb: ["psb", "pickup success behaviours", "pickup success behaviors", "pickup success"],
  phr: ["phr", "preference honour rate", "preference honor rate"],
  reattempts: ["reattempts", "reattempt compliance", "reattempt"],
  podFails: ["pod fails", "pod fail", "pod rejects"],
  ccFails: ["cc fails", "cc fail", "contact failures"],
};
