"use client";
import { useMemo,useRef,useState } from "react";
import {analyseFiles} from "../../lib/analyzer";
import {IMPORT_ACCEPT} from "../../lib/imports/preflight";
import { ErrorBox,Loading,dname,filterRowsBySite,n,openShape,pct,trid,useOperationalRows,weekNo } from "./OperationalShared";
const weekOf=r=>{const raw=String(r?.raw_data?.calendar_week||r?.week_label||"");const m=raw.match(/W\d+/i);return m?m[0].toUpperCase():raw},detailOf=r=>r?.raw_data?.contact_compliance_detail||{},esc=v=>'"'+String(v??"").replaceAll('"','""')+'"';
export default function CustomerComplianceView({organizationId,onOpenDriver,onImported,siteFilter="all",refreshKey=0}){
 const load=useOperationalRows(organizationId,"cc",refreshKey),rows=filterRowsBySite(load.rows,siteFilter).filter(r=>String(r?.raw_data?.metric_granularity||"weekly")==="weekly"),[week,setWeek]=useState(""),[query,setQuery]=useState(""),[detail,setDetail]=useState(null),[sort,setSort]=useState({key:"cc",dir:"desc"}),[showTrid,setShowTrid]=useState(false),[cleared,setCleared]=useState(false),[importing,setImporting]=useState(false),[importMessage,setImportMessage]=useState(""),input=useRef(null);
 const weeks=useMemo(()=>[...new Set(rows.map(weekOf).filter(w=>/^W\d+$/i.test(w)))].sort((a,b)=>weekNo(b)-weekNo(a)),[rows]),selectedWeek=week&&weeks.includes(week)?week:(weeks[0]||""),selected=useMemo(()=>cleared?[]:rows.filter(r=>weekOf(r)===selectedWeek&&n(r.cc)!=null).sort((a,b)=>Number(b.cc)-Number(a.cc)),[rows,selectedWeek,cleared]),filtered=selected.filter(r=>`${dname(r.drivers)} ${trid(r.drivers)}`.toLowerCase().includes(query.toLowerCase())),sortValue=(r,key)=>{const d=detailOf(r);if(key==="name")return dname(r.drivers).toLowerCase();if(key==="trid")return trid(r.drivers);if(key==="required")return n(d.required)??-1;if(key==="completed")return n(d.completed)??-1;if(key==="missed")return n(d.missed)??-1;if(key==="status")return Number(r.cc);return Number(r.cc)},sorted=[...filtered].sort((a,b)=>{const av=sortValue(a,sort.key),bv=sortValue(b,sort.key),cmp=typeof av==="string"?av.localeCompare(bv):av-bv;return sort.dir==="asc"?cmp:-cmp}),toggleSort=key=>setSort(v=>({key,dir:v.key===key&&v.dir==="asc"?"desc":"asc"})),arrow=key=>sort.key===key?(sort.dir==="asc"?" ↑":" ↓"):" ↕",active=detail||sorted[0]||null;
 const totals=selected.reduce((a,r)=>{const d=detailOf(r),req=n(d.required),done=n(d.completed),miss=n(d.missed);if(req!=null)a.required+=req;if(done!=null)a.completed+=done;if(miss!=null)a.missed+=miss;return a},{required:0,completed:0,missed:0}),overall=totals.required?totals.completed/totals.required*100:(selected.length?selected.reduce((s,r)=>s+Number(r.cc||0),0)/selected.length:null),below=selected.filter(r=>Number(r.cc)<98).length,band=v=>v>=99?"excellent":v>=98?"target":v>=95?"risk":"critical",label=v=>v>=99?"Excellent":v>=98?"On target":v>=95?"Needs improvement":"Critical",reasons=active?detailOf(active).reasons||[]:[],grouped=Object.entries(reasons.reduce((a,x)=>{const k=x.reason||"Other";a[k]=(a[k]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]);
 const clearPage=()=>{setCleared(true);setDetail(null);setQuery("");setImportMessage("")};
 const quickImport=async file=>{if(!file||importing)return;setImporting(true);setImportMessage("Analysing "+file.name+"…");try{const result=await analyseFiles([file]);if(!result?.recognizedFiles)throw new Error("This file was not recognised as a supported report.");const types=(result.fileResults||[]).filter(x=>x.recognized).map(x=>String(x.reportType||"").toLowerCase());if(types.length&&!types.some(x=>x.includes("contact")||x.includes("compliance")))throw new Error("This is not a Customer Compliance report. Use Import Center for mixed or bulk imports.");await onImported?.(result,[file]);setCleared(false);setWeek("");setDetail(null);setImportMessage("Customer Compliance report imported successfully.");}catch(e){setImportMessage(e?.message||"Could not import Customer Compliance report.");}finally{setImporting(false);if(input.current)input.current.value=""}};
 const exportCsv=()=>{const h=["Driver","TRID","Required","Completed","Missed","Compliance %","Status"],b=filtered.map(r=>{const d=detailOf(r);return[dname(r.drivers),trid(r.drivers),d.required,d.completed,d.missed,r.cc,label(Number(r.cc))]}),blob=new Blob([[h,...b].map(x=>x.map(esc).join(",")).join("\r\n")],{type:"text/csv"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`metrixiq-contact-compliance-${selectedWeek}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),300)};
 if(load.loading)return <Loading text="Loading Customer Contact Compliance…"/>;if(load.error)return <ErrorBox error={load.error}/>;
 return <div className="ccv2"><div className="ccv2-head"><div><span className="page-kicker">CUSTOMER COMPLIANCE</span><h1>Customer Contact Compliance</h1><p>Track how many customer contacts were required, completed and missed.</p></div><div className="ccv2-target"><i>◎</i><div><b>Target &gt;= 98%</b><span>Complete customer contact when required.</span></div></div></div>
 <section className="ccv2-kpis"><article><i>▥</i><div><span>Total Required Contacts</span><strong>{totals.required||"—"}</strong><small>Addresses requiring contact</small></div></article><article className="ok"><i>●</i><div><span>Completed Contacts</span><strong>{totals.completed||"—"}</strong><small>Successfully contacted</small></div></article><article className="bad"><i>!</i><div><span>Missed Contacts</span><strong>{totals.missed||0}</strong><small>Not contacted</small></div></article><article><div className="ccv2-ring"><b>{pct(overall,1)}</b></div><div><span>Overall Compliance</span><strong>{pct(overall,1)}</strong><small>Selected week</small></div></article><article><i>♙</i><div><span>Drivers Below Target</span><strong>{below} / {selected.length}</strong><small>Drivers &lt; 98%</small></div></article></section>
 {importMessage&&<div className="ccv2-import-message">{importMessage}</div>}<section className="ccv2-toolbar"><select value={selectedWeek} onChange={e=>setWeek(e.target.value)}>{weeks.map(w=><option key={w}>{w}</option>)}</select><div className="ccv2-site">{siteFilter==="all"?"All sites":siteFilter}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="⌕  Search driver name or TRID…"/><button className="btn ghost" onClick={()=>setShowTrid(v=>!v}>{showTrid?"Hide TRID":"Show TRID"}</button><button className="btn ghost" onClick={exportCsv}>⇩ Export</button><input ref={input} type="file" hidden accept={IMPORT_ACCEPT} onChange={e=>quickImport(e.target.files?.[0])}/><button className="btn primary" disabled={importing} onClick={()=>input.current?.click()}>{importing?"Importing…":"⇧ Import Report"}</button><button className="btn danger" onClick={clearPage}>⌫ Clear page</button></section>
 <section className="ccv2-body"><article className="panel ccv2-table"><div className="table-wrap"><table><thead><tr><th>#</th><th onClick={()=>toggleSort("name")}>Driver Name{arrow("name")}</th>{showTrid&&<th onClick={()=>toggleSort("trid")}>TRID{arrow("trid")}</th>}<th onClick={()=>toggleSort("required")}>Addresses (Required){arrow("required")}</th><th onClick={()=>toggleSort("completed")}>Contacts Completed{arrow("completed")}</th><th onClick={()=>toggleSort("missed")}>Missed{arrow("missed")}</th><th onClick={()=>toggleSort("cc")}>Compliance %{arrow("cc")}</th><th onClick={()=>toggleSort("status")}>Status{arrow("status")}</th><th>Action</th></tr></thead><tbody>{sorted.map((r,i)=>{const d=detailOf(r),v=Number(r.cc);return <tr key={r.driver_id+"-"+i} className={active===r?"active":""} onClick={()=>setDetail(r)}><td>{i+1}</td><td><b>{dname(r.drivers)}</b></td>{showTrid&&<td><code>{trid(r.drivers)}</code></td>}<td>{d.required??"—"}</td><td>{d.completed??"—"}</td><td className={Number(d.missed)>0?"missed":""}>{d.missed??"—"}</td><td><strong>{pct(v,2)}</strong></td><td><span className={"ccv2-band "+band(v)}>{label(v)}</span></td><td><button onClick={e=>{e.stopPropagation();setDetail(r);setTimeout(()=>document.querySelector(".ccv2-detail")?.scrollIntoView({behavior:"smooth",block:"start"}),0)}}>View</button></td></tr>})}</tbody></table></div><footer>Showing {filtered.length} of {selected.length} drivers</footer></article>
 <aside className="panel ccv2-detail">{active?<><div className="ccv2-driver"><div className="driver-avatar">{dname(active.drivers).split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><h2>{dname(active.drivers)}</h2>{showTrid&&<p>TRID: {trid(active.drivers)}</p>}</div><button onClick={()=>setDetail(null)}>×</button></div><div className={"ccv2-score "+band(Number(active.cc))}><strong>{pct(active.cc,2)}</strong><span>Customer Contact Compliance</span><p><b>{detailOf(active).completed??"—"} of {detailOf(active).required??"—"}</b> required contacts completed<br/>{detailOf(active).missed??"—"} missed contacts</p></div><div className="ccv2-mini"><article><b>{detailOf(active).required??"—"}</b><span>Required</span></article><article><b>{detailOf(active).completed??"—"}</b><span>Completed</span></article><article><b>{detailOf(active).missed??"—"}</b><span>Missed</span></article><article><b>{pct(active.cc,2)}</b><span>Compliance</span></article></div><h3>Main Reason Codes</h3><div className="ccv2-reasons">{grouped.length?grouped.map(([k,v])=><p key={k}><span>{k}</span><b>{v}</b></p>):<p><span>No reason-code detail in this import</span></p>}</div>{reasons.length?<details><summary>View non-compliant deliveries ({reasons.length})</summary><div className="ccv2-tracking">{reasons.map((x,i)=><p key={i}><span>{x.reason||"—"}</span><code>{x.trackingId||"—"}</code></p>)}</div></details>:null}<button className="btn primary full" onClick={()=>onOpenDriver?.(openShape(active,{cc:n(active.cc),risk:Number(active.cc)<95?"High":Number(active.cc)<98?"Medium":"Low"}))}>Open Driver 360 →</button></>:<div className="v10-empty">Select a driver to view compliance details.</div>}</aside></section></div>
}