"use client";
import {useMemo,useRef,useState} from "react";
import {analyseFiles} from "../../lib/analyzer";
import {IMPORT_ACCEPT} from "../../lib/imports/preflight";
import {ErrorBox,Loading,dname,filterRowsBySite,n,openShape,pct,trid,useOperationalRows,weekNo} from "./OperationalShared";
const weekOf=r=>{const x=String(r?.raw_data?.calendar_week||r?.week_label||"");return x.match(/W\d+/i)?.[0]?.toUpperCase()||x};
const podOf=r=>r?.raw_data?.pod_detail||{};
const reasons=[["noPackageDetected","No Package Detected","▣"],["blurryPhoto","Blurry Photo","◉"],["photoTooDark","Photo Too Dark","◐"],["packageInCar","Package In Car","▰"],["packageTooClose","Package Too Close","⌕"]];
const sum=(a,f)=>a.reduce((s,x)=>s+(Number(f(x))||0),0),band=v=>v>=99.8?"excellent":v>=99.6?"target":v>=99?"risk":"critical",label=v=>v>=99.8?"Excellent":v>=99.6?"On target":v>=99?"At risk":"Critical",csv=v=>'"'+String(v??"").replaceAll('"','""')+'"';
export default function PodQualityView({organizationId,onOpenDriver,onImported,siteFilter="all",refreshKey=0}){
 const load=useOperationalRows(organizationId,"pod",refreshKey),rows=filterRowsBySite(load.rows,siteFilter),input=useRef(null);
 const [week,setWeek]=useState(""),[q,setQ]=useState(""),[focus,setFocus]=useState("all"),[reason,setReason]=useState("all"),[sort,setSort]=useState({key:"rejects",dir:"desc"}),[detail,setDetail]=useState(null),[cleared,setCleared]=useState(false),[importing,setImporting]=useState(false),[importMessage,setImportMessage]=useState("");
 const weeks=useMemo(()=>[...new Set(rows.filter(r=>r.raw_data?.pod_detail).map(weekOf).filter(x=>/^W\d+$/i.test(x)))].sort((a,b)=>weekNo(b)-weekNo(a)),[rows]),selectedWeek=week&&weeks.includes(week)?week:(weeks[0]||"");
 const base=cleared?[]:rows.filter(r=>r.raw_data?.pod_detail&&weekOf(r)===selectedWeek),totals={opp:sum(base,r=>podOf(r).opportunities),success:sum(base,r=>podOf(r).success),bypass:sum(base,r=>podOf(r).bypass),rejects:sum(base,r=>podOf(r).rejects)};totals.pod=totals.opp?totals.success/totals.opp*100:null;
 const reasonTotals=Object.fromEntries(reasons.map(([k])=>[k,sum(base,r=>podOf(r).reasons?.[k])]));
 const mainReason=r=>{const d=podOf(r),x=d.reasons||{},m=reasons.map(([k,l])=>[l,Number(x[k])||0]).sort((a,b)=>b[1]-a[1])[0];return m?.[1]?m[0]:(Number(d.rejects)>0?"Reason unavailable":Number(d.bypass)>0?"Bypass":"—")};
 const val=(r,k)=>{const d=podOf(r);if(k==="name")return dname(r.drivers).toLowerCase();if(k==="trid")return trid(r.drivers);if(k==="pod")return Number(r.pod)||0;return Number(d[k])||0};
 const filtered=base.filter(r=>{const d=podOf(r),v=Number(r.pod)||0;return (dname(r.drivers)+" "+trid(r.drivers)).toLowerCase().includes(q.toLowerCase())&&(focus==="all"||(focus==="rejects"&&d.rejects>0)||(focus==="bypass"&&d.bypass>0)||(focus==="below"&&v<99)||(focus==="excellent"&&v>=99.8))&&(reason==="all"||(d.reasons?.[reason]||0)>0)}).sort((a,b)=>{const av=val(a,sort.key),bv=val(b,sort.key),c=typeof av==="string"?av.localeCompare(bv):av-bv;return sort.dir==="asc"?c:-c});
 const active=detail&&base.includes(detail)?detail:(filtered[0]||null),ad=podOf(active),ar=ad.reasons||{},toggle=k=>setSort(s=>({key:k,dir:s.key===k&&s.dir==="desc"?"asc":"desc"})),arrow=k=>sort.key===k?(sort.dir==="desc"?" ↓":" ↑"):"";
 const clear=()=>{setCleared(true);setDetail(null);setQ("");setFocus("all");setReason("all");setImportMessage("")};
 const quickImport=async file=>{if(!file||importing)return;setImporting(true);setImportMessage("Analysing "+file.name+"…");try{const result=await analyseFiles([file]);if(!result?.recognizedFiles)throw new Error("This file was not recognised as a supported report.");const types=(result.fileResults||[]).filter(x=>x.recognized).map(x=>String(x.reportType||"").toLowerCase());if(types.length&&!types.some(x=>x.includes("pod")))throw new Error("This is not a POD report. Use Import Center for mixed or bulk imports.");await onImported?.(result,[file]);setCleared(false);setWeek("");setDetail(null);setImportMessage("POD report imported successfully.");}catch(e){setImportMessage(e?.message||"Could not import POD report.");}finally{setImporting(false);if(input.current)input.current.value=""}};
 const exportCsv=()=>{const h=["Driver","TRID","Opportunities","Success","Bypass","Rejects","POD %","Main reject reason"],b=filtered.map(r=>[dname(r.drivers),trid(r.drivers),podOf(r).opportunities,podOf(r).success,podOf(r).bypass,podOf(r).rejects,r.pod,mainReason(r)]),blob=new Blob([[h,...b].map(x=>x.map(csv).join(",")).join("\r
")],{type:"text/csv"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="metrixiq-pod-"+selectedWeek+".csv";a.click();setTimeout(()=>URL.revokeObjectURL(u),300)};
 if(load.loading)return <Loading text="Loading POD quality…"/>;if(load.error)return <ErrorBox error={load.error}/>;
 return <div className="podv2"><header className="podv2-head"><div><span className="page-kicker">DELIVERY QUALITY</span><h1>Photo-on-Delivery Compliance</h1><p>Track POD quality by driver, reject reason and coaching priority.</p></div><div className="podv2-actions"><select value={selectedWeek} onChange={e=>{setWeek(e.target.value);setCleared(false);setDetail(null)}}>{weeks.map(w=><option key={w}>{w}</option>)}</select><input ref={input} type="file" hidden accept={IMPORT_ACCEPT} onChange={e=>quickImport(e.target.files?.[0])}/><button className="btn primary" disabled={importing} onClick={()=>input.current?.click()}>{importing?"Importing…":"⇧ Import Report"}</button><button className="btn ghost" onClick={exportCsv}>⇩ Export</button><button className="btn danger" onClick={clear}>⌫ Clear page</button></div></header>
 {importMessage&&<div className="podv2-import-message">{importMessage}</div>}
 {cleared?<section className="panel podv2-empty"><b>Page cleared</b><p>Ready for another POD week. Saved reports were not deleted.</p><button className="btn primary" disabled={importing} onClick={()=>input.current?.click()}>{importing?"Importing…":"⇧ Import another report"}</button></section>:<>
 <section className="podv2-kpis">{[["▣","Total Opportunities",totals.opp],["✓","Successful Photos",totals.success,pct(totals.pod,2)],["↻","Bypass",totals.bypass,totals.opp?pct(totals.bypass/totals.opp*100,2):"—"],["!","Rejects",totals.rejects,totals.opp?pct(totals.rejects/totals.opp*100,2):"—"]].map((x,i)=><article key={x[1]} className={i===3?"bad":i===2?"warn":"ok"}><i>{x[0]}</i><div><span>{x[1]}</span><strong>{Number(x[2]||0).toLocaleString()}</strong><small>{x[3]||selectedWeek}</small></div></article>)}</section>
 <section className="panel podv2-reasons"><h2>Reject Reasons <small>Total {totals.rejects}</small></h2><div className="podv2-reason-grid">{reasons.map(([k,l,ico])=><button key={k} onClick={()=>setReason(reason===k?"all":k)} className={reason===k?"active":""}><i>{ico}</i><span>{l}</span><b>{reasonTotals[k]}</b><small>{totals.rejects?((reasonTotals[k]/totals.rejects)*100).toFixed(1):0}%</small></button>)}</div></section>
 <nav className="podv2-chips">{[["all","All Drivers"],["rejects","With Rejects"],["bypass","With Bypass"],["below","POD < 99%"],["excellent","Excellent ≥ 99.8%"]].map(([k,l])=><button key={k} className={focus===k?"active":""} onClick={()=>setFocus(k)}>{l}</button>)}</nav>
 <div className="podv2-filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="⌕ Search driver name or Transporter ID…"/><select value={reason} onChange={e=>setReason(e.target.value)}><option value="all">All reject reasons</option>{reasons.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select value={sort.key} onChange={e=>setSort({key:e.target.value,dir:"desc"})}><option value="rejects">Sort: Rejects</option><option value="pod">Sort: POD</option><option value="bypass">Sort: Bypass</option><option value="opportunities">Sort: Opportunities</option></select></div>
 <section className="podv2-lower"><article className="panel podv2-table"><div className="table-wrap"><table><thead><tr><th>#</th>{[["name","Driver Name"],["trid","Transporter ID"],["opportunities","Opportunities"],["success","Success"],["bypass","Bypass"],["rejects","Rejects"],["pod","POD %"]].map(([k,l])=><th key={k} onClick={()=>toggle(k)}>{l}{arrow(k)}</th>)}<th>Main Reject Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map((r,i)=>{const d=podOf(r),v=Number(r.pod)||0;return <tr key={r.driver_id+"-"+i} className={active===r?"active":""} onClick={()=>setDetail(r)}><td>{i+1}</td><td><b>{dname(r.drivers)}</b></td><td><code>{trid(r.drivers)}</code></td><td>{d.opportunities}</td><td>{d.success}</td><td className={d.bypass?"warn":""}>{d.bypass}</td><td className={d.rejects?"bad":""}>{d.rejects}</td><td><b>{pct(v,2)}</b></td><td>{mainReason(r)}</td><td><span className={"podv2-band "+band(v)}>{label(v)}</span></td><td><button onClick={e=>{e.stopPropagation();setDetail(r)}}>View</button></td></tr>})}</tbody></table></div><footer>Showing {filtered.length} drivers · click headers to sort ↑/↓</footer></article>
 <aside className="panel podv2-detail">{active?<><div className="podv2-driver"><div className="driver-avatar">{dname(active.drivers).split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><h2>{dname(active.drivers)}</h2><p>{trid(active.drivers)}</p></div><button onClick={()=>setDetail(null)}>×</button></div><div className="podv2-mini">{[["Opportunities",ad.opportunities],["Success",ad.success],["Bypass",ad.bypass],["Rejects",ad.rejects]].map(x=><article key={x[0]}><b>{x[1]??0}</b><span>{x[0]}</span></article>)}</div><div className={"podv2-score "+band(Number(active.pod)||0)}><strong>{pct(active.pod,2)}</strong><span>POD Quality</span></div><h3>Reject Reasons</h3><div className="podv2-detail-reasons">{reasons.map(([k,l,ico])=><p key={k}><span>{ico} {l}</span><b>{ar[k]||0}</b></p>)}</div><div className="podv2-coach"><b>Coaching Focus</b><p>{mainReason(active)==="No Package Detected"?"Ensure the parcel is clearly visible and fully inside the delivery photo.":mainReason(active)==="Blurry Photo"?"Hold the device steady and confirm the photo is sharp before completing delivery.":mainReason(active)==="Photo Too Dark"?"Use better lighting and make sure the parcel and delivery location are visible.":mainReason(active)==="Package In Car"?"Take the POD only after the parcel is at the delivery location, not inside the vehicle.":mainReason(active)==="Package Too Close"?"Step back so the full parcel and delivery context are visible.":"Review POD process and avoid manual bypass where a valid photo can be taken."}</p></div><button className="btn ghost full" onClick={()=>navigator.clipboard?.writeText(dname(active.drivers)+" POD coaching: "+mainReason(active)+". POD "+pct(active.pod,2)+".")}>Copy Coaching Message</button><button className="btn primary full" onClick={()=>onOpenDriver?.(openShape(active,{pod:n(active.pod)}))}>View Driver 360 →</button></>:<p>Select a driver.</p>}</aside></section></>}</div>
}